const routes={
  home:{name:'Home',url:'index.html'},
  products:[
    {key:'web',name:'Web Hosting',url:'web-hosting.html'},
    {key:'wordpress',name:'WordPress Hosting',url:'wordpress-hosting.html'},
    {key:'vps',name:'VPS',url:'vps.html'},
    {key:'dedicated',name:'Dedicated Servers',url:'dedicated-servers.html'},
    {key:'lifetime',name:'Lifetime Hosting',url:'lifetime-hosting.html'}
  ],
  client:'https://redprohost.com/panel/register.php',
  contact:'https://demo.redprohost.com/contact-us/',
  ticket:'https://redprohost.com/panel/submitticket.php',
  knowledge:'https://redprohost.com/panel/knowledgebase.php',
  cart:'https://redprohost.com/panel/cart.php',
  domain:'https://redprohost.com/panel/cart.php?a=add&domain=register'
};

const sharedPlans=[
  ['Starter Plan','$9.99','/yearly',['1 Website','5 GB NVME storage*','30 GB Bandwidth Monthly','2 FTP Accounts','5 Email Acoounts','6 databases Allowed','5 Subdomains Allowed','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/starter-plan'],
  ['Advanced Plan','$12.99','/yearly',['2 Website','10 GB NVME storage*','40 GB Bandwidth Monthly','4 FTP Accounts','10 Email Acoounts','13 databases Allowed','10 Subdomains Allowed','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/advanced-plan'],
  ['PRO Plan','$19.99','/yearly',['3 Website','15 GB NVME storage*','50 GB Bandwidth Monthly','6 FTP Accounts','15 Email Acoounts','20 databases Allowed','15 Subdomains Allowed','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/pro-plan'],
  ['Elite Plan','$39.99','/yearly',['5 Website','20 GB NVME storage*','80 GB Bandwidth Monthly','8 FTP Accounts','20 Email Acoounts','30 databases Allowed','20 Subdomains Allowed','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/elite-plan'],
  ['Ultra Plan','$49.99','/yearly',['free .com Domain','Unlimited Websites','Unlimited NVME storage*','Unlimited Bandwidth Monthly','Unlimited FTP Accounts','Unlimited Email Acoounts','Unlimited databases Allowed','Unlimited Subdomains Allowed','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/ultra-plan'],
  ['Max Power plan','$65.99','/yearly',['Everything Ultra Plan Included','Extra CPU Resources','Special setup for WordPress','Free .com Domain','More Powerful','100% Uptime','Unlimited databases Allowed','Unlimited Websites','Free, unlimited SSL for all your websites**'],'https://redprohost.com/panel/store/web-hosting/max-power']
];

const vpsPlans=[
  ['Starter VPS','$12.50','/Mo',['CPU Speed: 1 v COre','CPU Threats: 2c/8t','Memory: 2GB','Storage 20 GB SSD','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/st-vps'],
  ['Value VPS','$16.00','/Mo',['CPU Speed: 1 v COre','CPU Threats: 2c/8t','Memory: 2GB','Storage 40 GB SSD NVMe','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/va-vps'],
  ['Essential VPS','$34.00','/Mo',['CPU Speed: 2 v COre','CPU Threats: 2c/8t','Memory: 4GB','Storage 80 GB SSD NVMe','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/es-vps'],
  ['Comfort VPS','$54.00','/Mo',['CPU Speed: 4 v COre','CPU Threats: 2c/8t','Memory: 8GB','Storage 160 GB SSD NVMe','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/co-vps'],
  ['Elite VPS','$80.00','/Mo',['CPU Speed: 8 v COre','CPU Threats: 2c/8t','Memory: 8GB to 32 GB','Storage 160 GB to 640 GB SSD NVMe','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/el-vps'],
  ['HH1','$9.50','/Mo',['CPU Speed: 1 AMD EPYC Milan core','CPU Threats: 2c/8t','Memory: 2GB','Storage 10 GB SSD','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/hh-1-plan'],
  ['HH2','$17.00','/Mo',['CPU Speed: 2AMD EPYC Milan core','CPU Threats: 2c/8t','Memory: 4GB','Storage 20 GB SSD NVMe','Bandwidth: Unlimited','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/hh-2-plan'],
  ['HH3','$36.00','/Mo',['CPU Speed: 2AMD EPYC Milan core','CPU Threats: 2c/8t','Memory: 8GB','Storage: 35 GB SSD NVMe','Bandwidth: Unlimited','Additional IPs: Available'],'https://redprohost.com/panel/store/vps-deals/hh-3-plan'],
  ['HH4','$70.00','/Mo',['CPU Speed: 4x2.8+GHz Core','CPU threats: 2c/8t','Memory: 16 GB','Storage: 75 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/hh-4-plan'],
  ['HH5','$105.00','/Mo',['CPU Speed: 6x2.8+GHz Core','CPU threats: 2c/8t','Memory: 24 GB','Storage: 100 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/hh-5-plan'],
  ['HH6','$145.00','/Mo',['CPU Speed: 8x2.8+GHz Core','CPU threats: 2c/8t','Memory: 32 GB','Storage: 125 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/hh-6-plan'],
  ['HH7','$210.00','/Mo',['CPU Speed: 12x2.8+GHz Core','CPU threats: 2c/8t','Memory: 48 GB','Storage: 150 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/hh-7-plan'],
  ['HH8','$290.00','/Mo',['CPU Speed: 16x2.8+GHz Core','CPU threats: 2c/8t','Memory: 64 GB','Storage: 100 GB or 400 SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/hh-8-plan'],
  ['CB Value','$86.00','/Mo',['CPU Speed: 6v CPU Core','CPU threats: 2c/8t','Memory: 16 GB','Storage: 100 GB or 400 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/cb-value-plan'],
  ['CB Starter','$15.00','/Mo',['CPU Speed: 4v CPU Core','CPU threats: 2c/8t','Memory: 8 GB','Storage: 50 GB or 200 GB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://redprohost.com/panel/store/vps-deals/cb-starter-plan'],
  ['CB Comfort','$131.00','/Mo',['CPU Speed: 10v CPU Core','CPU threats: 2c/8t','Memory: 60 GB','Storage: 400 GB or 1.6 TB SSD NVMe','Bandwidth Unlimited','Additional IPs Available'],'https://www.redprohost.com/panel/store/vps-deals/cb-comfort-plan']
];

const dedicatedPlans=[
  ['Intel Xeon E3-1225v2','$100.00','/month',['CPU SPeed: 3.2GHz /3.6GHz','CPU Threats:4c / 8t','Memory: 16 GB','Storage: 3x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-sat-1-16','Order Now'],
  ['Intel Xeon E5-1630v3 ssd','$170.00','/month',['CPU SPeed: 3.7GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 64 GB','Storage: 2×480 GB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e5-ssd-1-64','Order Now'],
  ['Intel Xeon E5-1630v3','$170.00','/month',['CPU SPeed: 3.7GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 64 GB','Storage: 4x2 TB sata','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e5-sat-1-64','Order Now'],
  ['Intel Xeon E3-1231v3','$160.00','/month',['CPU SPeed: 3.4GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 32 GB','Storage: 4x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-sat-2-32','Click here'],
  ['Intel Xeon E3-1231V3','$110.00','/month',['CPU SPeed: 3.4GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 32 GB','Storage:4x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-sat-1-32','Order Now'],
  ['Intel Xeon D-1520','$160.00','/month',['CPU SPeed: 2.2GHz /2.6GHz','CPU Threats:4c / 8t','Memory: 32 GB','Storage: 2×480 GB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-ssd-2-32','Order Now'],
  ['Intel Xeon D-1520','$110.00','/month',['CPU SPeed:3.4GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 32 GB','Storage: 2×480 GB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-ssd-1-32','Order Now'],
  ['Intel Xeon E3-SAT-1-32','$110.00','/month',['CPU SPeed:3.2GHz /3.6GHz','CPU Threats:4c / 8t','Memory: 16 GB','Storage: 3x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-sat-1-32','Order Now'],
  ['Intel Xeon E3-1225v2','$100.00','/month',['CPU SPeed:3.2GHz /3.6GHz','CPU Threats:4c / 8t','Memory: 16 GB','Storage: 3x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://redprohost.com/panel/store/dedicated-servers/e3-sat-1-16','Oeder Now'],
  ['Intel Xeon E3-1245v2','$120.00','/month',['CPU SPeed:3.4GHz /3.8GHz','CPU Threats:4c / 8t','Memory: 16 GB','Storage: 3x2 TB','Bandwidth: 250 MBIT','Additional IPs: Available'],'https://www.redprohost.com/panel/store/dedicated-servers/e3-sat-1-3x2','Order Now']
];

const lifetimePlans=[
  ['Lifetime Launch','$99','one-time payment',['1 website','3GB NVMe storage','30GB monthly bandwidth','2 databases','5 email accounts','150,000 inodes','1 CPU and 1GB RAM','10 entry processes','Free SSL certificates','Weekly backups','Friendly hosting support'],'https://redprohost.com/panel/cart.php?a=add&pid=34','Choose Lifetime Launch'],
  ['Lifetime Scale','$249','one-time payment',['Up to 5 websites','15GB NVMe storage','150GB monthly bandwidth','10 databases','25 email accounts','300,000 inodes','2 CPU and 2GB RAM','20 entry processes','Free SSL certificates','Weekly backups','Friendly hosting support'],'https://redprohost.com/panel/cart.php?a=add&pid=35','Choose Lifetime Scale','MOST POPULAR'],
  ['Lifetime Prime','$499','one-time payment',['Up to 15 websites','40GB NVMe storage','400GB monthly bandwidth','30 databases','75 email accounts','500,000 inodes','3 CPU and 3GB RAM','30 entry processes','Free SSL certificates','Weekly backups','Friendly hosting support'],'https://redprohost.com/panel/cart.php?a=add&pid=36','Choose Lifetime Prime']
];

const commonFaq={
  web:[
    ['What is web hosting, and why do I need it?','Web hosting is a service that stores your website files and makes them accessible on the internet. Without hosting, your website cannot be viewed by visitors online. RedProHost offers fast, secure, and reliable hosting to ensure your site is always up and running.'],
    ['What types of hosting does RedProHost offer?','We provide a variety of hosting options including Shared Hosting, VPS Hosting, and Dedicated Servers. Each plan is designed to meet different needs, from small personal blogs to high-traffic business websites.'],
    ['How do I choose the right hosting plan?','Choosing the right plan depends on your website size, expected traffic, and performance needs. Small websites can start with shared hosting, while larger businesses or online stores may benefit from VPS or dedicated hosting.'],
    ['Is website migration to RedProHost free?','Yes! We offer free website migration from your current host to RedProHost. Our experts handle the entire process smoothly, ensuring no downtime or data loss during the transfer.'],
    ['How reliable is RedProHost’s uptime?','We guarantee 99.9% uptime, meaning your website stays online almost all the time. Our advanced infrastructure and monitoring systems ensure maximum reliability and performance for your site.'],
    ['Does RedProHost provide customer support?','Absolutely! Our support team is available 24/7 via live chat, email, and ticket system.'],
    ['Will my website be secure with RedProHost?','Yes, all our hosting plans come with free SSL certificates, advanced firewalls, DDoS protection, and regular malware scans.'],
    ['Can I host multiple websites on one account?','Yes, depending on the plan you choose. Our higher-tier plans allow you to host multiple domains from a single control panel.'],
    ['Do you offer backups for websites?','Yes, we provide automated daily and weekly backups to protect your data.'],
    ['Can I upgrade my hosting plan later?','Definitely! RedProHost allows easy plan upgrades as your website grows without downtime.']
  ],
  wordpress:[
    ['What is WordPress Hosting?','WordPress hosting is web hosting specially optimized for running WordPress websites. At RedProHost, our servers are fine-tuned for maximum speed, security, and reliability.'],
    ['How is WordPress Hosting different from regular hosting?','Regular hosting can run many platforms, but WordPress hosting is optimized specifically for WordPress. This means faster load times, enhanced security, and pre-installed features.'],
    ['Can I migrate my existing WordPress site to RedProHost?','Yes! We offer free website migration. Our experts will handle the entire process for you without any downtime or technical hassle.'],
    ['Is WordPress Hosting beginner-friendly?','Absolutely. We provide a simple control panel, one-click WordPress installation, and 24/7 support.'],
    ['Do you provide automatic updates for WordPress?','Yes. RedProHost automatically updates WordPress core, themes, and plugins to keep your site secure and up to date.'],
    ['How secure is my WordPress website with RedProHost?','We use advanced firewalls, malware scanning, and daily backups to keep your site protected from hackers and data loss.'],
    ['Can I host multiple WordPress websites on one plan?','Yes, depending on your selected plan. Our higher-tier WordPress hosting packages allow multiple site hosting under one account.'],
    ['Will my website be fast with WordPress Hosting?','Definitely. Our servers are optimized with SSD storage, caching, and CDN integration.'],
    ['Do you offer 24/7 support for WordPress issues?','Yes, our expert support team is available 24/7 via live chat, email, and phone.'],
    ['What if I need to upgrade my plan later?','Upgrading is quick and easy. You can scale up your hosting plan anytime.']
  ],
  vps:[
    ['What is VPS Hosting?','VPS (Virtual Private Server) Hosting is a type of hosting where you get a dedicated portion of a physical server. It offers more power, control, and flexibility than shared hosting.'],
    ['How is VPS different from shared hosting?','Unlike shared hosting, VPS provides dedicated resources like CPU, RAM, and storage.'],
    ['Do I need technical knowledge to use VPS hosting?','You can choose between managed VPS or unmanaged VPS. Managed VPS is beginner-friendly and supported by our expert team.'],
    ['Can I install custom software on my VPS?','Yes, with full root access, you can install any software or scripts needed for your website or application.'],
    ['How scalable is VPS Hosting?','VPS hosting is highly scalable. You can upgrade CPU, RAM, or storage resources easily.'],
    ['Is VPS hosting secure?','Yes, VPS offers an isolated environment with enhanced security measures such as firewalls, DDoS protection, and daily backups.'],
    ['What operating systems are available with VPS?','We offer popular Linux distributions including Ubuntu and CentOS, plus Windows Server editions.'],
    ['Will my website experience downtime during upgrades?','No. Upgrading your VPS resources is seamless and designed to avoid downtime.'],
    ['Do you offer backups for VPS?','Yes, we provide automated daily backups.'],
    ['How can I get support for my VPS?','Our expert support team is available 24/7 via live chat, email, and phone.']
  ],
  dedicated:[
    ['What is a dedicated server?','A dedicated server is a hosting solution where an entire physical server is allocated to you alone.'],
    ['Why should I choose a dedicated server over shared hosting?','With a dedicated server, you get more power, speed, and control compared to shared hosting.'],
    ['Who needs a dedicated server?','Businesses, e-commerce stores, gaming servers, or any platform that requires high performance, strong security, and full customization.'],
    ['Is a dedicated server faster than VPS hosting?','Yes, dedicated servers generally offer more speed and consistent performance because all server resources are 100% yours.'],
    ['Can I upgrade my dedicated server later?','Absolutely! You can add more RAM, storage, or processing power as your needs grow.'],
    ['Are dedicated servers secure?','Yes, they’re highly secure. Since you’re not sharing the server, the risk of other users affecting your data is eliminated.'],
    ['Do I get full control over the server?','Yes, with root or admin access, you can configure your server exactly how you want.'],
    ['What operating systems can I run on a dedicated server?','You can choose from various OS options, including Linux distributions and Windows Server editions.'],
    ['Do you offer managed dedicated servers?','Yes, you can choose managed hosting so we handle maintenance, updates, and monitoring.'],
    ['How much does a dedicated server cost?','Pricing depends on server specifications, location, and management level.']
  ],
  lifetime:[
    ['What makes this hosting different?','It combines NVMe hosting, LiteSpeed delivery, free SSL, cPanel, weekly backups, defined resources and support with a one-time charge for the included base hosting service.'],
    ['Is there a money-back guarantee?','Eligible hosting purchases include a 30-day refund period, subject to the published refund policy. Domains, third-party licenses, completed services and other non-hosting charges may be non-refundable.'],
    ['How is my website protected?','Plans include SSL certificates, server security controls, account isolation, monitoring and weekly remote restore points.'],
    ['Can I upgrade later?','Yes. You can move to a larger plan or an eligible resource add-on when your requirements increase.'],
    ['Is website migration included?','One eligible cPanel or WordPress website migration is included after activation.'],
    ['Will my website load quickly?','NVMe storage, LiteSpeed delivery and WordPress cache compatibility support fast loading. Results also depend on website optimization.'],
    ['Are professional email accounts included?','Yes. Lifetime Launch includes 5 email accounts, Lifetime Scale includes 25 and Lifetime Prime includes 75.'],
    ['Can I host more than one website?','Lifetime Launch supports one website, Lifetime Scale supports up to five and Lifetime Prime supports up to fifteen.'],
    ['What support is available?','Support is available for account setup, hosting questions and technical issues through the client area.'],
    ['Can I register a new domain?','Yes. Domain registration is separate from lifetime hosting and renews at the registrar’s current renewal price.'],
    ['Can I transfer a domain I already own?','Yes. Select the domain-transfer option during checkout. Transfer fees and eligibility are confirmed before payment.']
  ]
};

const pageData={
  home:{eyebrow:'Domains & Hosting',h1:'Domains & Hosting, Made Simple.',description:'Fast, secure hosting with clear plans, dependable performance and support ready when you need it.',image:'https://redprohost.com/wp-content/uploads/2024/05/wordpress-2-1024x793.png',facts:['From $9.99/year','Free SSL','24/7 support']},
  web:{eyebrow:'Red Pro Host',h1:'Fast, Reliable & Affordable Web Hosting for Your Success',description:'Launch your website with speed, security, and 24/7 expert support. Whether you’re running a personal blog or a business site, our hosting is built to keep you online and growing.',plans:sharedPlans,image:'https://redprohost.com/wp-content/uploads/2025/08/Web-Hosting.png',facts:['From $9.99/year','NVMe storage','Free SSL']},
  wordpress:{eyebrow:'WordPress Hosting',h1:'WordPress Hosting – Fast, Secure, and Made for Your Success',description:'Power your WordPress website with RedProHost’s optimized hosting solutions. Enjoy lightning-fast load times, top-tier security, automatic updates, and expert WordPress support—so you can focus on growing your site while we handle the rest.',plans:[sharedPlans[0],sharedPlans[4],sharedPlans[2],sharedPlans[1],sharedPlans[5],sharedPlans[3]],image:'https://redprohost.com/wp-content/uploads/2025/08/Wordpress-Hosting.png',facts:['1-click install','Automatic updates','Daily backups']},
  vps:{eyebrow:'VPS Hosting',h1:'Unlock Ultimate Power & Control with RedProHost VPS Hosting.',description:'Experience dedicated resources, full server control, and scalable performance tailored to your growing business needs. Perfect for developers, high-traffic sites, and custom applications.',plans:vpsPlans,image:'https://redprohost.com/wp-content/uploads/2025/08/VPS-server.png',facts:['From $9.50/mo','Full root access','Dedicated resources']},
  dedicated:{eyebrow:'RedProHost',h1:'Unleash Maximum – Power & Control with Dedicated Servers',description:'Experience the ultimate hosting solution designed for high-traffic websites, resource-heavy applications, and businesses that demand top-tier performance and security. With RedProHost Dedicated Servers, you get complete control, unmatched reliability, and 24/7 expert support.',plans:dedicatedPlans,image:'https://redprohost.com/wp-content/uploads/2025/08/dedicated-server.png',facts:['From $100/month','Full admin access','250 MBIT']},
  lifetime:{eyebrow:'Lifetime Web Hosting',h1:'Pay once. Keep your website online for the long run.',description:'Launch your website on fast NVMe hosting with cPanel, free SSL, weekly backups and reliable support—without a recurring base hosting bill.',plans:lifetimePlans,facts:['From $99 once','NVMe storage','cPanel included']}
};

function currentUrl(key){return key==='home'?routes.home.url:routes.products.find(p=>p.key===key)?.url}
function header(key){
  const links=routes.products.map(p=>`<a data-hosting-product-link ${p.key===key?'aria-current="page"':''} href="${p.url}">${p.name}</a>`).join('');
  return `<header class="site-header" data-hosting-site-header><div class="container nav-wrap"><a class="brand" href="${routes.home.url}"><img src="https://redprohost.com/wp-content/uploads/2025/02/logo_site_mbl.png" alt="RedProHost"><span>RedProHost</span></a><nav class="desktop-nav" aria-label="Primary"><a class="nav-link" ${key==='home'?'aria-current="page"':''} href="${routes.home.url}">Home</a><div class="products-menu"><button class="products-toggle" type="button" aria-expanded="false">Hosting</button><div class="dropdown">${links}</div></div><a class="nav-link account-link" href="${routes.client}">Client Area</a></nav><button class="mobile-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu">☰</button></div><nav id="mobile-menu" class="mobile-panel" aria-label="Mobile"><a href="${routes.home.url}">Home</a>${links}<a href="${routes.client}">Client Area</a></nav></header>`;
}
function hero(key,data){
  const rows=routes.products.map(p=>`<a class="product-row" data-hosting-product-link href="${p.url}" ${p.key===key?'aria-current="page"':''}><span>${p.name}</span><span aria-hidden="true">↗</span></a>`).join('');
  const visual=data.image?`<div class="hero-image-frame"><img src="${data.image}" alt="${data.eyebrow}" fetchpriority="high"></div>`:`<div class="lifetime-mark"><span>∞</span><strong>$99</strong><small>one-time hosting</small></div>`;
  return `<section class="hero hero-${key}" data-hosting-page-hero><div class="container"><div class="hero-grid"><div class="hero-copy" data-hosting-hero-content><p class="eyebrow"><span></span>${data.eyebrow}</p><h1>${data.h1}</h1><p>${data.description}</p><div class="hero-facts">${data.facts.map(f=>`<span>${f}</span>`).join('')}</div><form class="domain-form" data-hosting-domain-search action="https://redprohost.com/" method="get"><label class="sr-only" for="domain-${key}">Domain name</label><input id="domain-${key}" name="domain" type="text" placeholder="Enter domain name" required><label class="sr-only" for="tld-${key}">TLD</label><select id="tld-${key}" name="tld"><option value="com">.com</option><option value="net">.net</option></select><button data-hosting-primary-cta type="submit">Search Domain</button></form></div><aside class="hero-visual" aria-label="${data.eyebrow}">${visual}<div class="visual-label"><span>REDPROHOST</span><strong>${data.facts[0]}</strong></div></aside></div><nav class="product-dock" data-hosting-top-products aria-label="Top Products"><span class="dock-title">Explore hosting</span>${rows}</nav></div></section>`;
}
function plans(title,intro,items){return `<section class="section alt" id="plans"><div class="container"><div class="section-head"><div><p class="kicker">Hosting plans</p><h2>${title}</h2><p>${intro}</p></div></div><div class="plans-grid">${items.map((p,i)=>`<article class="plan-card ${p[6]?'featured':''}">${p[6]?`<span class="plan-badge">${p[6]}</span>`:''}<h3>${p[0]}</h3><p class="price">${p[1]}</p><p class="term">${p[2]}</p><ul>${p[3].map(f=>`<li>✓ ${f}</li>`).join('')}</ul><a class="plan-action" data-hosting-primary-cta href="${p[4]}">${p[5]||'Order Now'}</a></article>`).join('')}</div></div></section>`}
function cards(title,intro,items,alt=false){return `<section class="section ${alt?'alt':''}"><div class="container"><div class="section-head"><div><p class="kicker">Features</p><h2>${title}</h2><p>${intro}</p></div></div><div class="grid-4">${items.map((x,i)=>`<article class="feature-card"><span class="icon">${String(i+1).padStart(2,'0')}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>`}
function media(title,body,image,bullets=[]){return `<section class="section"><div class="container media-split"><div><p class="kicker">Red Pro Host</p><h2>${title}</h2><p>${body}</p>${bullets.length?`<ul class="check-list">${bullets.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}</div><img src="${image}" alt="${title}"></div></section>`}
function faq(key){return `<section class="section alt" id="faqs"><div class="container"><div class="section-head"><div><p class="kicker">FAQs</p><h2>${key==='lifetime'?'Everything you should know before choosing.':'Have questions? We\'ve got answers.'}</h2></div></div><div class="faq-list">${commonFaq[key].map((x,i)=>`<article class="faq-item ${i===0?'open':''}"><button class="faq-question" type="button" aria-expanded="${i===0}">${x[0]}<span aria-hidden="true">+</span></button><div class="faq-answer"><p>${x[1]}</p></div></article>`).join('')}</div></div></section>`}
function closing(title,body,url,label){return `<section class="section"><div class="container"><div class="cta-band"><div><p class="kicker">Ready to launch?</p><h2>${title}</h2><p>${body}</p></div><a class="btn-secondary" href="${url}">${label}</a></div></div></section>`}

function homeContent(){
  const features=[['Blazing-Fast Performance','High-performance SSD storage, powerful processors, and optimized server configurations deliver quick load times.'],['99.99% Uptime Guarantee','Rock-solid infrastructure and advanced monitoring keep your website online.'],['Free SSL Security','Every hosting plan includes a free SSL certificate to protect visitors and support SEO.'],['24/7 Expert Support','Friendly, knowledgeable support is available around the clock.'],['Easy-To-Use Control Panel','Manage websites, domains, files, emails, and databases from a beginner-friendly control panel.'],['Scalable Hosting Solutions','Upgrade your plan as your traffic and business expand.']];
  const categoryPlans=[['Web Hosting','$9.99','/year',['1 Website','5 GB NVMe Storage','Free SSL Certificate'],'web-hosting.html','View Products'],['WordPress Hosting','$9.99','/year',['1 WordPress Website','5 GB NVMe Storage','Automatic WordPress Updates'],'wordpress-hosting.html','View Products'],['VPS Hosting','$9.50','/month',['1 AMD EPYC Milan Core','2 GB RAM','10 GB SSD Storage'],'vps.html','View Products'],['Dedicated Servers','$100','/month',['Intel Xeon E3-1225v2','16 GB RAM','3 × 2 TB Storage'],'dedicated-servers.html','View Products']];
  const homeFaq=[['What Makes RedProHost Different From Other Hosting Providers?','RedProHost stands out for its combination of high performance, 24/7 expert support, and affordable pricing.'],['Do You Offer A Money-Back Guarantee?','New Shared and WordPress Hosting purchases include a 30-day money-back guarantee, while new Lifetime Hosting purchases include a 7-day money-back guarantee. VPS and Dedicated Servers become non-refundable once provisioning begins.'],['How Secure Is My Website With RedProHost?','All plans include free SSL certificates, advanced DDoS protection, daily backups, and continuous server monitoring.'],['Can I Upgrade My Hosting Plan Later?','You can start with a smaller plan and upgrade anytime as your website grows.'],['Do You Provide Free Website Migration?','Yes, we offer free website migration for new customers.'],['Will My Website Be Fast With RedProHost?','Our servers use SSD technology, optimized caching, and high-speed networking.'],['Do You Provide Email Hosting With Your Plans?','Yes, all hosting plans include professional email accounts.'],['Can I Host Multiple Websites On One Plan?','Yes, depending on the hosting plan you choose.'],['What Kind Of Support Do You Offer?','We provide 24/7 customer support via live chat, email, and ticket system.'],['Do You Offer Domain Registration Along With Hosting?','Yes. You can register a new domain, transfer your existing one, or get a free domain with selected hosting plans.']];
  commonFaq.home=homeFaq;
  return `${media('Built For Speed And Security.','Perfect for personal websites, blogs, and small businesses, our Shared Hosting gives you fast loading speeds, reliable uptime, and powerful features — all without breaking your budget.','https://redprohost.com/wp-content/uploads/2024/05/wordpress-2-1024x793.png',['50% OFF your first year — same renewal price, no hidden fees','Easy cPanel control for quick site management','Optimized for WordPress & Magento','Weekly backups & free migration from your old host','24/7 expert support ready to help anytime'])}${plans('Choose the right plan for your website','Fast NVMe hosting, free SSL, dependable performance, and plans built to grow with you.',categoryPlans)}${cards('Why Choose RedProHost?','Every feature is built with your success in mind, whether you’re launching a personal blog or managing a large e-commerce store.',features)}${media('Lightning-Fast Performance You Can See','Our advanced server technology, SSD storage, and optimized network ensure your site loads quickly. Faster load times mean happier visitors, better SEO rankings, and more conversions.','https://redprohost.com/wp-content/uploads/2026/08/11.png',['Next-Gen Hardware','Global CDN','Optimized for WordPress & More','99.99% Uptime Guarantee'])}${media('Free & Hassle-Free Website Migration','Our migration experts handle everything — from moving files and databases to making sure emails work after the transfer.','https://redprohost.com/wp-content/uploads/2026/08/22.png',['Your website stays live during the move','Files, databases, and emails are migrated','Smooth and secure transfer','Migration is free for new customers'])}${faq('home')}`;
}

function productContent(key){
  const d=pageData[key];
  if(key==='web') return `${plans('Choose The Hosting Plan That Fits Your Website','Fast NVMe hosting, free SSL, dependable performance, and plans built to grow with you.',d.plans)}${media('What Kind Of Sites Need Business Hosting?','Web Hosting Plus is the perfect solution for those who need the power of a VPS but want the simplicity of shared hosting.','https://redprohost.com/wp-content/uploads/2025/08/Web-Hosting.png',['Boosted Performance','No Technical Headaches','Better Uptime','Room to Grow'])}${cards('Built for demanding websites','Performance and resources for busy stores, high-traffic websites, and resource-intensive projects.',[['A Fast Track To More Sales.','Dedicated resources keep high-traffic eCommerce browsing and checkout smooth.'],['Build The Ultimate Online Shopping Experience.','Speed, stability, and power help stores handle busy sales periods.'],['Power To The People.','More CPU, RAM, and storage for complex applications and heavy databases.']])}${faq(key)}`;
  if(key==='wordpress') return `${plans('WordPress Hosting Pricing Plans','Each plan is crafted to give you maximum performance, speed, and security without breaking your budget.',d.plans)}${cards('All Plans Include','Everything needed for a smooth, fast, and secure WordPress experience.',[['Free SSL Certificate','Secure your site with HTTPS at no extra cost.'],['Automatic WordPress Updates','Stay protected and up-to-date without lifting a finger.'],['1-Click WordPress Installation','Get your site live in minutes with a simple setup.'],['Daily Backups','Restore your site from automated backups.'],['Free Website Migration','Our experts move your site for free.'],['Optimized WordPress Performance','Servers are tuned specifically for WordPress.'],['24/7 Expert Support','WordPress specialists are always ready to help.'],['Enhanced Security Protection','Protection from malware and brute-force attacks.'],['Easy-to-Use Control Panel','Manage your site, emails, and settings from one dashboard.']])}${cards('WordPress Hosting Features','Speed, security, and support designed around WordPress.',[['WordPress-Optimized Servers','Fine-tuned servers deliver fast load times and smooth performance.'],['99.9% Uptime Guarantee','Reliable infrastructure keeps your site online.'],['Free & Easy Website Migration','Migration experts handle the switch for free.'],['24/7 WordPress Expert Support','Friendly technical help is available day and night.'],['Security You Can Rely On','Firewalls, malware scans, and proactive monitoring protect your site.'],['Affordable Plans Without Compromise','Premium features at prices for beginners and professionals.']],true)}${faq(key)}`;
  if(key==='vps') return `${plans('VPS Hosting Plans','Dedicated resources, scalable capacity, and full server control.',d.plans)}${media('Powerful Hosting Built for Your eCommerce Success','Launch your online store with reliable, high-performance hosting. Our optimized hosting supports WooCommerce, Magento, and other major eCommerce platforms.','https://redprohost.com/wp-content/uploads/2025/08/8.png',['Full Root Access','Dedicated CPU & RAM','99.9% Uptime Guarantee','24/7 Expert Support'])}${cards('All Self Managed & Managed VPS Hosting Plans Include:','Powerful, isolated resources with the flexibility to configure your environment.',[['Dedicated Resources','Guaranteed CPU, RAM, and storage dedicated to your website or application.'],['Full Root Access','Install software and configure your VPS without restrictions.'],['Scalability','Upgrade CPU, RAM, or storage as your website grows.'],['Enhanced Security','Firewalls, DDoS protection, and malware scanning keep data safe.'],['SSD Storage','Fast SSD drives improve read/write speeds and loading times.'],['Choice of Operating Systems','Choose Linux distributions or Windows Server.']])}${faq(key)}`;
  if(key==='dedicated') return `${plans('Dedicated Server Plans','Choose the hardware, storage, memory, and bandwidth your workloads require.',d.plans)}${media('Powerful Servers Built for Peak Performance','Our dedicated servers are equipped to handle demanding workloads with fast storage and dependable infrastructure.','https://redprohost.com/wp-content/uploads/2025/08/8.png',['Cutting-Edge Processors','High-Capacity SSD Storage','Generous RAM','Unmetered Bandwidth','Advanced RAID Configurations'])}${cards('RedProHost Dedicated Server Features','Robust infrastructure and expert support help critical applications run smoothly.',[['High-Performance Hardware','Intel Xeon and AMD EPYC processors deliver speed and reliability.'],['Massive SSD Storage with RAID','SSD storage with RAID improves performance and protects data.'],['Full Root/Admin Access','Install custom software and manage your environment.'],['Unlimited Bandwidth','Unmetered transfer accommodates large traffic volumes.'],['Advanced Security Measures','Firewalls, DDoS protection, malware scanning, and monitoring.'],['Customizable Configurations','Choose your operating system, control panel, and software.'],['99.99% Uptime Guarantee','Reliable availability keeps applications accessible.'],['Automated Backups','Regular backups make recovery practical.'],['24/7 Expert Support','Server specialists assist with setup and troubleshooting.']])}${cards('Benefits of Choosing Dedicated Servers','Power, control, and security designed for growing businesses.',[['Unmatched Performance','The full power of a physical server is dedicated to your business.'],['Complete Control','Root access lets you configure the server to your needs.'],['Scalability','Upgrade hardware and resources as the business grows.'],['Reliable Uptime','Dependable infrastructure supports constant availability.'],['Expert Support','Technical assistance is available around the clock.']],true)}${faq(key)}`;
  return `${plans('Select the capacity that fits your websites.','Every plan includes NVMe hosting, free SSL, weekly backups, cPanel access and support.',d.plans)}<section class="section"><div class="container"><div class="stats"><div class="stat"><strong>NVMe</strong>Storage</div><div class="stat"><strong>cPanel</strong>Control panel</div><div class="stat"><strong>Free SSL</strong>Security</div><div class="stat"><strong>Weekly</strong>Backups</div></div><p>Prices exclude domain registration, premium software, managed maintenance, dedicated IPs and optional add-ons. Each order includes one cPanel account. Separately isolated client accounts may require an annual agency add-on.</p></div></section>${cards('A practical home for websites built to last.','Choose capacity for one focused project, a growing business collection or a larger portfolio of client websites.',[['Business websites','Keep your company website fast, secure and easy to manage.'],['Creators and professionals','Host portfolios, blogs and service websites with WordPress-ready tools.'],['Designers and studios','Manage multiple websites with higher storage, bandwidth and processing resources.']])}${cards('Performance, protection and control in one place.','Essential hosting features work together to keep your website responsive, protected and manageable.',[['NVMe performance','Fast storage and LiteSpeed-powered delivery help pages respond quickly.'],['Included security','Free SSL certificates protect visitor connections.'],['Dependable availability','Infrastructure and monitoring support consistent availability.'],['Easy cPanel control','Manage files, domains, email, databases, SSL and WordPress.'],['Weekly backups','Remote restore points provide practical recovery options.'],['Website migration','One eligible cPanel or WordPress migration is included.']],true)}${media('What does “lifetime hosting” mean?','Your one-time payment covers the included base hosting service for the lifetime of the lifetime-hosting service. It does not refer to the biological lifetime of an individual.','https://redprohost.com/wp-content/uploads/2025/02/logo_site_mbl.png',['Accounts must remain active, follow the Acceptable Use Policy and stay within published limits.','Domain names, premium licenses, managed maintenance, additional resources and optional services are separate products.'])}${cards('Get online in three straightforward steps.','From checkout to launch.',[['Choose your capacity','Compare website limits, storage, bandwidth and processing resources.'],['Activate your account','Complete checkout and receive your cPanel details after review.'],['Launch or migrate','Install WordPress or request the included migration.']])}${faq(key)}`;
}

function footer(){return `<footer class="site-footer" data-hosting-site-footer><div class="container"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="${routes.home.url}"><img src="https://redprohost.com/wp-content/uploads/2025/02/logo_site_mbl.png" alt="RedProHost"><span>RedProHost</span></a><p>Powering your websites with speed, security, and reliability. Your trusted hosting partner, 24/7.</p><p>+1 (330) 362-9223<br>Info@Redprohost.Com<br>10 Tupeck Lane Center Tuftonboro NH 3816 United States</p></div><div><h2>Products</h2>${routes.products.map(p=>`<a data-hosting-product-link href="${p.url}">${p.name}</a>`).join('')}</div><div><h2>Company</h2><a href="${routes.contact}">Contact Us</a><a href="${routes.client}">Client Area</a></div><div><h2>Support</h2><a href="${routes.ticket}">Submit Ticket</a><a href="${routes.knowledge}">Knowledge Base</a></div><div><h2>Orders</h2><a href="${routes.domain}">Domain Register</a><a href="${routes.cart}">Order Of Service</a></div></div><div class="footer-bottom">Copyright © 2025, RedProHost All Rights Reserved.</div></div></footer>`}

const pageKey=document.body.dataset.page;
const data=pageData[pageKey];
document.getElementById('site-header').innerHTML=header(pageKey);
document.getElementById('content').innerHTML=hero(pageKey,data)+(pageKey==='home'?homeContent():productContent(pageKey))+closing(pageKey==='lifetime'?'Give your website a faster, longer-lasting home.':'Looking For Assistance?','Contact Our Acclaimed Customer Support At +1 (330) 362-9223.',pageKey==='lifetime'?'lifetime-hosting.html#plans':routes.contact,pageKey==='lifetime'?'View Lifetime Plans':'Contact Us');
document.getElementById('site-footer').innerHTML=footer();

const mobileToggle=document.querySelector('.mobile-toggle');
const mobilePanel=document.querySelector('.mobile-panel');
mobileToggle.addEventListener('click',()=>{const open=mobileToggle.getAttribute('aria-expanded')==='true';mobileToggle.setAttribute('aria-expanded',String(!open));mobilePanel.classList.toggle('is-open',!open)});
document.querySelectorAll('.faq-question').forEach(button=>button.addEventListener('click',()=>{const item=button.closest('.faq-item');const open=item.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));
